### Tạo món ăn mới có ảnh
POST http://localhost:3000/api/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUwNzEzNDczLCJleHAiOjE3NTA3OTk4NzN9.Z1IT500NXPpAK3-BxzUU4pJrtsnp3_klOEQGaUpEEI4
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="name"

Bún bò Huế
--MyBoundary
Content-Disposition: form-data; name="price"

45000
--MyBoundary
Content-Disposition: form-data; name="category_id"

1
--MyBoundary
Content-Disposition: form-data; name="image"; filename="js.png"
Content-Type: image/png

< ./js.png
--MyBoundary--